const express = require('express');
const cors = require('cors');
require('dotenv').config();

const app = express();

// 🎯 CORS FIX: Vercel har naye deployment pe alag URL deta hai
const allowedOrigins = [
  /^https:\/\/.*\.vercel\.app$/,
  'http://localhost:5173',
  'http://localhost:3000',
];

app.use(cors({
  origin: function (origin, callback) {
    if (!origin) return callback(null, true);
    const isAllowed = allowedOrigins.some((pattern) =>
      pattern instanceof RegExp ? pattern.test(origin) : pattern === origin
    );
    if (isAllowed) {
      callback(null, true);
    } else {
      callback(new Error('Not allowed by CORS: ' + origin));
    }
  }
}));

app.use(express.json());

app.get('/', (req, res) => {
  res.send('🚀 Sevanta Minerals Backend is Live and Running!');
});

app.post('/api/send-lead', async (req, res) => {
  const { name, email, countryCode, phone, companyName, service, budget, projectDetails } = req.body;
  const currentDateTime = new Date().toLocaleString("en-US", { timeZone: "Asia/Kolkata" });

  const emailSubject = `💎 B2B Lead Alert: ${name} | ${service || 'New Request'}`;

  const emailHtmlBody = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <style>
        body { font-family: 'Segoe UI', sans-serif; background: #f4f1ea; margin: 0; padding: 40px 15px; }
        .wrapper { max-width: 600px; margin: 0 auto; background: #ffffff; border-radius: 16px; box-shadow: 0 10px 30px rgba(156, 111, 58, 0.1); border: 1px solid rgba(184, 135, 79, 0.2); overflow: hidden; }
        .header { background: linear-gradient(135deg, #1e272e, #0f1418); padding: 35px 30px; text-align: center; border-bottom: 4px solid #b8874f; }
        .header h1 { margin: 0; color: #ffffff; font-size: 24px; font-weight: 700; letter-spacing: 1.5px; text-transform: uppercase; }
        .header p { margin: 8px 0 0 0; color: #b8874f; font-size: 13px; font-weight: 600; letter-spacing: 2px; text-transform: uppercase; }
        .body-content { padding: 35px 30px; }
        .data-table { width: 100%; border-collapse: separate; border-spacing: 0; margin-bottom: 30px; border: 1px solid #ead7bc; border-radius: 10px; overflow: hidden; }
        .data-table tr td { padding: 15px 18px; font-size: 14px; border-bottom: 1px solid #fff5e6; }
        .label-column { background-color: #fffdf9; font-weight: 600; color: #9c6f3a; width: 38%; }
        .value-column { background-color: #ffffff; color: #2c3e50; }
        .requirements-box { background: #fffdf9; border: 1px solid #ead7bc; border-left: 4px solid #b8874f; border-radius: 8px; padding: 20px; font-size: 14px; color: #4f4f4f; line-height: 1.6; white-space: pre-wrap; }
        .footer-bar { background-color: #1e272e; padding: 22px; text-align: center; font-size: 11px; color: #8a8a8a; }
      </style>
    </head>
    <body>
      <div class="wrapper">
        <div class="header">
          <h1>Lead Details Form</h1>
          <p>Sevanta Minerals Internal Portal</p>
        </div>
        <div class="body-content">
          <p style="font-size:13px;color:#7f8c8d;">Received: ${currentDateTime}</p>
          <table class="data-table">
            <tbody>
              <tr><td class="label-column">👤 Client Name</td><td class="value-column">${name}</td></tr>
              <tr><td class="label-column">📧 Email</td><td class="value-column">${email}</td></tr>
              <tr><td class="label-column">📞 Phone</td><td class="value-column">${countryCode ? countryCode + ' ' : ''}${phone}</td></tr>
              <tr><td class="label-column">🏢 Company</td><td class="value-column">${companyName || 'Not Provided'}</td></tr>
              <tr><td class="label-column">🛠️ Service</td><td class="value-column">${service || 'General Enquiry'}</td></tr>
              <tr><td class="label-column">💰 Budget</td><td class="value-column">${budget || 'N/A'}</td></tr>
            </tbody>
          </table>
          <p style="font-weight:700;">📝 Detailed Requirements</p>
          <div class="requirements-box">${projectDetails || 'No specific technical parameters described.'}</div>
        </div>
        <div class="footer-bar">This is an automated sales notification generated by Sevanta Minerals Hub.</div>
      </div>
    </body>
    </html>
  `;

  try {
    // 🎯 FIX: Gmail SMTP (nodemailer) hataya — Render ke network se Gmail SMTP
    // reliably connect nahi ho pa raha tha (ENETUNREACH / ETIMEDOUT).
    // Ab Resend ka HTTPS API use kar rahe hain, jo SMTP use hi nahi karta,
    // isliye ye issue completely bypass ho jaata hai.
    const resendResponse = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${process.env.RESEND_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: 'Sevanta Minerals <onboarding@resend.dev>', // domain verify karne ke baad apna email use karna
        to: ['vickysoni5111@gmail.com'], // ⚠️ TEMPORARY - domain verify karne ke baad Sevantaminerals@gmail.com kar dena
        reply_to: email,
        subject: emailSubject,
        html: emailHtmlBody,
      }),
    });

    const resendData = await resendResponse.json();

    if (!resendResponse.ok) {
      console.error('Resend API Error:', resendData);
      return res.status(500).json({ success: false, error: 'Failed to send email' });
    }

    res.status(200).json({ success: true, message: 'Lead sent successfully!' });
  } catch (error) {
    console.error('Send-lead Error:', error);
    res.status(500).json({ success: false, error: 'Internal Server Error' });
  }
});

const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`🚀 Server fully operational on port ${PORT}`));